app = "kinjar-api"
primary_region = "atl"

[env]
  PORT = "8080"
  DATA_DIR = "/data"
  ALLOWED_ORIGINS = "https://slaughterbeck.kinjar.com,https://www.kinjar.com,https://kinjar.com,http://localhost:3000"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  # Increase limits for file uploads (in seconds)
  [http_service.http_options]
    response_timeout = 300
    idle_timeout = 300
    # Gunicorn only speaks HTTP/1.1; disable HTTP/2 backend to avoid invalid preface requests
    h2_backend = false

  [[http_service.checks]]
    interval = "30s"
    timeout  = "10s"
    grace_period = "120s"
    method = "GET"
    path = "/health"
    protocol = "http"

[mounts]
  source = "data"
  destination = "/data"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
